-- ===================================================================
-- Migração V3: Criar tabela de tokens de reset de senha
-- Data: 2025-10-14
-- Descrição: Armazena tokens de reset com expiração e controle de uso
-- Tarefa: 2 - Recuperação de Senha por Email
-- ===================================================================

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,  -- SHA-256 = 64 chars hex
    usuario_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT fk_password_reset_tokens_usuario 
        FOREIGN KEY (usuario_id) 
        REFERENCES usuarios(id) 
        ON DELETE CASCADE
);

-- Índices para performance
CREATE INDEX idx_password_reset_tokens_usuario_id ON password_reset_tokens(usuario_id);
CREATE INDEX idx_password_reset_tokens_token_hash ON password_reset_tokens(token_hash);
CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);

-- Comentários descritivos
COMMENT ON TABLE password_reset_tokens IS 'Tokens de recuperação de senha com expiração (Tarefa 2)';
COMMENT ON COLUMN password_reset_tokens.token_hash IS 'Hash SHA-256 do token (64 chars hex) - não BCrypt pois precisa lookup direto';
COMMENT ON COLUMN password_reset_tokens.usuario_id IS 'Referência ao usuário que solicitou o reset';
COMMENT ON COLUMN password_reset_tokens.expires_at IS 'Data/hora de expiração do token (30 minutos após criação)';
COMMENT ON COLUMN password_reset_tokens.used_at IS 'Quando o token foi usado (null = ainda não usado)';
COMMENT ON COLUMN password_reset_tokens.created_at IS 'Data/hora de criação do token';

