-- ===================================================================
-- Migração V4: Criar tabela de auditoria de reset de senha
-- Data: 2025-10-14
-- Descrição: Auditoria completa de tentativas (compliance LGPD)
-- Tarefa: 2 - Recuperação de Senha por Email
-- ===================================================================

CREATE TABLE password_reset_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    user_agent TEXT,
    event_type VARCHAR(50) NOT NULL,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    
    CONSTRAINT pk_password_reset_audit PRIMARY KEY (id)
);

-- Índices para análise e rate limiting
CREATE INDEX idx_password_reset_audit_email ON password_reset_audit(email);
CREATE INDEX idx_password_reset_audit_ip ON password_reset_audit(ip_address);
CREATE INDEX idx_password_reset_audit_timestamp ON password_reset_audit(timestamp);
CREATE INDEX idx_password_reset_audit_event_type ON password_reset_audit(event_type);
CREATE INDEX idx_password_reset_audit_email_timestamp ON password_reset_audit(email, timestamp);
CREATE INDEX idx_password_reset_audit_ip_timestamp ON password_reset_audit(ip_address, timestamp);

-- Comentários descritivos
COMMENT ON TABLE password_reset_audit IS 'Auditoria de tentativas de recuperação de senha (compliance LGPD)';
COMMENT ON COLUMN password_reset_audit.email IS 'Email usado na tentativa';
COMMENT ON COLUMN password_reset_audit.ip_address IS 'IP de origem (IPv4 ou IPv6)';
COMMENT ON COLUMN password_reset_audit.user_agent IS 'User-Agent do navegador/cliente';
COMMENT ON COLUMN password_reset_audit.event_type IS 'Tipo de evento: REQUEST, SUCCESS, FAILURE, EXPIRED_TOKEN, INVALID_TOKEN, RATE_LIMIT';
COMMENT ON COLUMN password_reset_audit.success IS 'Se a operação foi bem-sucedida';
COMMENT ON COLUMN password_reset_audit.error_message IS 'Mensagem de erro (se houver)';
COMMENT ON COLUMN password_reset_audit.timestamp IS 'Data/hora do evento';

