-- ===================================================================
-- Migração V5: Criação das tabelas RBAC (Role-Based Access Control)
-- Data: 2025-10-16
-- Descrição: Sistema completo de roles, permissões e pacotes de usuários
-- Fase: 3 - RBAC
-- ===================================================================

-- ===========================================
-- 1. TABELA ROLES
-- ===========================================

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT chk_role_name_format CHECK (name ~ '^[A-Z_]+$'),
    CONSTRAINT chk_role_name_length CHECK (LENGTH(name) >= 2 AND LENGTH(name) <= 50)
);

-- ===========================================
-- 2. TABELA PERMISSIONS
-- ===========================================

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    resource VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    
    CONSTRAINT pk_permissions PRIMARY KEY (id),
    CONSTRAINT chk_permission_name_format CHECK (name ~ '^[A-Z_]+$'),
    CONSTRAINT chk_permission_name_length CHECK (LENGTH(name) >= 2 AND LENGTH(name) <= 100),
    CONSTRAINT chk_resource_length CHECK (LENGTH(resource) >= 1 AND LENGTH(resource) <= 50)
);

-- ===========================================
-- 3. TABELA ROLE_PERMISSIONS (ManyToMany)
-- ===========================================

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role 
        FOREIGN KEY (role_id) 
        REFERENCES roles(id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission 
        FOREIGN KEY (permission_id) 
        REFERENCES permissions(id) 
        ON DELETE CASCADE
);

-- ===========================================
-- 4. TABELA USUARIO_ROLES (ManyToMany)
-- ===========================================

CREATE TABLE usuario_roles (
    usuario_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    
    CONSTRAINT pk_usuario_roles PRIMARY KEY (usuario_id, role_id),
    CONSTRAINT fk_usuario_roles_usuario 
        FOREIGN KEY (usuario_id) 
        REFERENCES usuarios(id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_roles_role 
        FOREIGN KEY (role_id) 
        REFERENCES roles(id) 
        ON DELETE CASCADE
);

-- ===========================================
-- 5. TABELA USUARIO_PACOTES (Metadados dos Pacotes)
-- ===========================================

CREATE TABLE usuario_pacotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id BIGINT NOT NULL UNIQUE,
    pacote_type VARCHAR(50) NOT NULL,
    limite_pacientes INTEGER,
    data_vencimento DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    permissoes_customizadas TEXT,
    observacoes VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    
    CONSTRAINT pk_usuario_pacotes PRIMARY KEY (id),
    CONSTRAINT fk_usuario_pacotes_usuario 
        FOREIGN KEY (usuario_id) 
        REFERENCES usuarios(id) 
        ON DELETE CASCADE,
    CONSTRAINT chk_pacote_type CHECK (pacote_type IN ('BASIC', 'PREMIUM', 'ENTERPRISE', 'CUSTOM')),
    CONSTRAINT chk_limite_pacientes CHECK (limite_pacientes IS NULL OR limite_pacientes >= 0)
);

-- ===========================================
-- ÍNDICES PARA PERFORMANCE
-- ===========================================

-- Roles
CREATE INDEX idx_roles_name ON roles(name);
CREATE INDEX idx_roles_active ON roles(active);

-- Permissions
CREATE INDEX idx_permissions_name ON permissions(name);
CREATE INDEX idx_permissions_resource ON permissions(resource);
CREATE INDEX idx_permissions_active ON permissions(active);

-- Role-Permissions
CREATE INDEX idx_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions(permission_id);

-- Usuario-Roles
CREATE INDEX idx_usuario_roles_usuario_id ON usuario_roles(usuario_id);
CREATE INDEX idx_usuario_roles_role_id ON usuario_roles(role_id);

-- Usuario-Pacotes
CREATE INDEX idx_usuario_pacotes_usuario_id ON usuario_pacotes(usuario_id);
CREATE INDEX idx_usuario_pacotes_pacote_type ON usuario_pacotes(pacote_type);
CREATE INDEX idx_usuario_pacotes_ativo ON usuario_pacotes(ativo);
CREATE INDEX idx_usuario_pacotes_data_vencimento ON usuario_pacotes(data_vencimento);

-- ===========================================
-- DADOS INICIAIS (ROLES E PERMISSÕES)
-- ===========================================

-- Inserir roles base
INSERT INTO roles (name, description) VALUES 
('ADMIN', 'Super usuário com acesso total ao sistema'),
('CLINICO', 'Usuário clínico base (sem pacote específico)');

-- Inserir permissões base
INSERT INTO permissions (name, description, resource) VALUES 
-- Permissões de pacientes
('READ_PATIENTS', 'Ler dados de pacientes', 'patients'),
('WRITE_PATIENTS', 'Criar/editar pacientes', 'patients'),
('DELETE_PATIENTS', 'Excluir pacientes', 'patients'),

-- Permissões de relatórios
('READ_BASIC_REPORTS', 'Acessar relatórios básicos', 'reports'),
('READ_ADVANCED_REPORTS', 'Acessar relatórios avançados', 'reports'),
('WRITE_REPORTS', 'Criar/editar relatórios', 'reports'),

-- Permissões de API
('API_ACCESS', 'Acesso à API externa', 'api'),
('API_WRITE', 'Escrita via API', 'api'),

-- Permissões de sistema
('MANAGE_USERS', 'Gerenciar usuários', 'system'),
('MANAGE_ROLES', 'Gerenciar roles e permissões', 'system'),
('SYSTEM_ADMIN', 'Administração do sistema', 'system'),

-- Permissões especiais
('WHITE_LABEL', 'Acesso a funcionalidades white-label', 'branding'),
('UNLIMITED_PATIENTS', 'Acesso ilimitado a pacientes', 'patients');

-- Configurar permissões do ADMIN (todas as permissões)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'ADMIN';

-- Configurar permissões básicas do CLINICO (sem pacote)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'CLINICO' 
AND p.name IN ('READ_PATIENTS', 'READ_BASIC_REPORTS');

-- ===========================================
-- COMENTÁRIOS DESCRITIVOS
-- ===========================================

COMMENT ON TABLE roles IS 'Roles do sistema RBAC (ADMIN, CLINICO, etc.)';
COMMENT ON TABLE permissions IS 'Permissões granulares do sistema (READ_PATIENTS, WRITE_REPORTS, etc.)';
COMMENT ON TABLE role_permissions IS 'Relacionamento ManyToMany entre roles e permissões';
COMMENT ON TABLE usuario_roles IS 'Relacionamento ManyToMany entre usuários e roles';
COMMENT ON TABLE usuario_pacotes IS 'Metadados dos pacotes de usuários (limites, vencimento, customizações)';

COMMENT ON COLUMN roles.name IS 'Nome da role (ADMIN, CLINICO, etc.) - deve ser maiúsculo';
COMMENT ON COLUMN permissions.name IS 'Nome da permissão (READ_PATIENTS, etc.) - deve ser maiúsculo';
COMMENT ON COLUMN permissions.resource IS 'Recurso relacionado (patients, reports, api, system)';
COMMENT ON COLUMN usuario_pacotes.pacote_type IS 'Tipo do pacote (BASIC, PREMIUM, ENTERPRISE, CUSTOM)';
COMMENT ON COLUMN usuario_pacotes.limite_pacientes IS 'Limite de pacientes (NULL = ilimitado)';
COMMENT ON COLUMN usuario_pacotes.data_vencimento IS 'Data de vencimento do pacote (NULL = sem vencimento)';
COMMENT ON COLUMN usuario_pacotes.permissoes_customizadas IS 'JSON com permissões customizadas para pacote CUSTOM';
